source "https://rubygems.org"

ruby ">= 3.0.0"

gem "rails", "~> 7.1"
gem "sqlite3", ">= 1.4"
gem "puma", ">= 5.0"
gem "bootsnap", require: false

group :development, :test do
  gem "debug", platforms: %i[ mri windows ]
end

group :development do
  gem "web-console"
end
