source 'https://rubygems.org'

gem 'rails', '4.2.7'
gem 'sqlite3', '~> 1.3.13'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks', '~> 2.5.0'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc

gem 'loofah', '~> 2.2.0'
gem 'rails-html-sanitizer', '~> 1.0.0'
gem 'rubocop', '~> 0.49.0', require: false

group :development, :test do
  gem 'byebug', '~> 9.0'
  gem 'minitest', '~> 5.10'
  gem 'test-unit', '~> 3.2'
end

group :development do
  gem 'web-console', '~> 2.0'
  gem 'spring', '~> 1.7.0'
end
