# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ec2a733eb3943e9e6dd389a9e022a86b0fa2b85a8bc24ed79a071d2bd2e2103a6f183d29d09a6b52485e974e4db55d56a0a46fd25310494c49a26c92e964070

test:
  secret_key_base: 8b43feb839fe07ca7d279d84a2f1b4c25578c6c01a17b93be52104ac87ccdbb167571244aea3b6bf679890918228a06f5b6f5bb04ffd91e53b74146e0302c92b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
