apiVersion: v1
kind: Secret
metadata:
  name: monitor-secrets
  namespace: ft-services
type: Opaque
data:
  influxdb-user: YWRtaW4=
  influxdb-password: YWRtaW4=
  grafana-user: YWRtaW4=
  grafana-password: YWRtaW4=
