#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
REPORT_DIR="$ROOT/reports"
OUT_MD="$REPORT_DIR/summary.md"

mkdir -p "$REPORT_DIR"

section() {
	local title="$1" file="$2"
	echo "## $title" >>"$OUT_MD"
	if [ -f "$file" ]; then
		echo "" >>"$OUT_MD"
		sed -n '1,40p' "$file" >>"$OUT_MD"
		echo "" >>"$OUT_MD"
	else
		echo "" >>"$OUT_MD"
		echo "_missing: $file_" >>"$OUT_MD"
		echo "" >>"$OUT_MD"
	fi
}

{
	echo "# ft_linux summary report"
	echo ""
	echo "generated: $(date '+%Y-%m-%d %H:%M:%S')"
	echo ""
} >"$OUT_MD"

section "Rootfs report" "$REPORT_DIR/rootfs_report.txt"
section "Fstab report" "$REPORT_DIR/fstab_report.txt"
section "Boot checklist" "$REPORT_DIR/boot_checklist.txt"
section "Host prereqs" "$REPORT_DIR/env_prereqs.txt"
section "Release report" "$REPORT_DIR/release_report.txt"
section "Grub report" "$REPORT_DIR/grub_report.txt"
section "Initramfs report" "$REPORT_DIR/initramfs_report.txt"
section "Services report" "$REPORT_DIR/services_report.txt"
section "Manifest lint" "$REPORT_DIR/manifest_report.txt"
section "Kernel config report" "$REPORT_DIR/kernel_config_report.txt"
section "Boot mode" "$REPORT_DIR/boot_mode.txt"
section "Boot finalize" "$REPORT_DIR/boot_finalize.txt"
section "Ready to boot" "$REPORT_DIR/ready_to_boot.txt"
section "Image report" "$REPORT_DIR/image_report.txt"
section "Boot archive" "$REPORT_DIR/boot_archive_report.txt"
section "Partition report" "$REPORT_DIR/partition_report.txt"
section "Release bundle" "$REPORT_DIR/release_bundle_report.txt"
section "Build state validation" "$REPORT_DIR/build_state_validation.txt"
section "Build state" "$REPORT_DIR/build_state.txt"
section "Build state sync" "$REPORT_DIR/build_state_sync.txt"
section "Build log audit" "$REPORT_DIR/build_log_audit.txt"
section "Manifest coverage" "$REPORT_DIR/manifest_coverage.txt"
section "Build plan" "$REPORT_DIR/build_plan.txt"
section "Build plan validation" "$REPORT_DIR/build_plan_validation.txt"
section "Build queue status" "$REPORT_DIR/build_queue_status.txt"
section "Build queue retry" "$REPORT_DIR/build_queue_retry_report.txt"
section "Build queue sync" "$REPORT_DIR/build_queue_sync.txt"
section "Build queue state" "$REPORT_DIR/build_queue_state_validation.txt"
section "Build queue metrics" "$REPORT_DIR/build_queue_metrics.txt"
section "Build queue failures" "$REPORT_DIR/build_queue_failures.txt"
section "Build queue report" "$REPORT_DIR/build_queue_report.txt"
section "Build state snapshot" "$REPORT_DIR/build_state_snapshot.txt"
section "Build state snapshots" "$REPORT_DIR/build_state_snapshots.txt"
section "Build state prune" "$REPORT_DIR/build_state_prune.txt"
section "Build plan split" "$REPORT_DIR/build_plan_splits.txt"
section "Build dashboard" "$REPORT_DIR/build_dashboard.txt"
section "Build plan remaining" "$REPORT_DIR/build_plan_remaining.txt"
section "Build progress" "$REPORT_DIR/build_progress.txt"
section "Build progress rollup" "$REPORT_DIR/build_progress_rollup.txt"
section "Build progress failures" "$REPORT_DIR/build_progress_failures.txt"
section "Build orchestrator report" "$REPORT_DIR/build_orchestrator_report.txt"
section "Build orchestrator status" "$REPORT_DIR/build_orchestrator_status.txt"
section "Build orchestrator validation" "$REPORT_DIR/build_orchestrator_validation.txt"
section "Build health report" "$REPORT_DIR/build_health_report.txt"
section "Build gate" "$REPORT_DIR/build_gate.txt"
section "Build summary JSON" "$REPORT_DIR/build_summary.json"
section "Build summary validate" "$REPORT_DIR/build_summary_validate.txt"
section "Build check report" "$REPORT_DIR/build_check_report.txt"
section "Build check status" "$REPORT_DIR/build_check_status_report.txt"
section "Build check rollup" "$REPORT_DIR/build_check_status_rollup.txt"
section "Build check gate" "$REPORT_DIR/build_check_gate.txt"
section "Build check trend" "$REPORT_DIR/build_check_trend.txt"
section "Build check prune" "$REPORT_DIR/build_check_prune.txt"
section "Build check stats" "$REPORT_DIR/build_check_stats.txt"
section "Build check summary JSON" "$REPORT_DIR/build_check_summary.json"
section "Build check summary validate" "$REPORT_DIR/build_check_summary_validate.txt"
section "Build check export CSV" "$REPORT_DIR/build_check_export.csv"
section "Build check coverage" "$REPORT_DIR/build_check_coverage.txt"
section "Build check snapshot" "$REPORT_DIR/build_check_snapshot.txt"
section "Build check snapshot list" "$REPORT_DIR/build_check_snapshot_list.txt"
section "Build check snapshot prune" "$REPORT_DIR/build_check_snapshot_prune.txt"
section "Build check snapshot diff" "$REPORT_DIR/build_check_snapshot_diff.txt"
section "Build times" "$REPORT_DIR/build_times.txt"
section "Status assessment" "$REPORT_DIR/status_assessment.txt"

echo "[OK] Summary report generated: $OUT_MD"
