#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
REPORT_DIR="$ROOT/reports"
OUT_MD="$REPORT_DIR/summary.md"

mkdir -p "$REPORT_DIR"

section() {
	local title="$1" file="$2"
	echo "## $title" >>"$OUT_MD"
	if [ -f "$file" ]; then
		echo "" >>"$OUT_MD"
		sed -n '1,40p' "$file" >>"$OUT_MD"
		echo "" >>"$OUT_MD"
	else
		echo "" >>"$OUT_MD"
		echo "_missing: $file_" >>"$OUT_MD"
		echo "" >>"$OUT_MD"
	fi
}

{
	echo "# ft_linux summary report"
	echo ""
	echo "generated: $(date '+%Y-%m-%d %H:%M:%S')"
	echo ""
} >"$OUT_MD"

section "Rootfs report" "$REPORT_DIR/rootfs_report.txt"
section "Preflight report" "$REPORT_DIR/preflight.txt"
section "Preflight JSON" "$REPORT_DIR/preflight.json"
section "Preflight validate" "$REPORT_DIR/preflight_validate.txt"
section "Preflight history" "$REPORT_DIR/preflight_history.txt"
section "Preflight trend" "$REPORT_DIR/preflight_trend.txt"
section "Preflight trend JSON" "$REPORT_DIR/preflight_trend.json"
section "Preflight gate" "$REPORT_DIR/build_preflight_gate.txt"
section "Preflight gate JSON" "$REPORT_DIR/build_preflight_gate.json"
section "Preflight gate validate" "$REPORT_DIR/build_preflight_gate_validate.txt"
section "Preflight gate history" "$REPORT_DIR/build_preflight_gate_history.txt"
section "Preflight gate trend" "$REPORT_DIR/build_preflight_gate_trend.txt"
section "Preflight gate trend JSON" "$REPORT_DIR/build_preflight_gate_trend.json"
section "Fstab report" "$REPORT_DIR/fstab_report.txt"
section "Boot checklist" "$REPORT_DIR/boot_checklist.txt"
section "Host prereqs" "$REPORT_DIR/env_prereqs.txt"
section "Release report" "$REPORT_DIR/release_report.txt"
section "Grub report" "$REPORT_DIR/grub_report.txt"
section "Initramfs report" "$REPORT_DIR/initramfs_report.txt"
section "Services report" "$REPORT_DIR/services_report.txt"
section "Manifest lint" "$REPORT_DIR/manifest_report.txt"
section "Kernel config report" "$REPORT_DIR/kernel_config_report.txt"
section "Boot mode" "$REPORT_DIR/boot_mode.txt"
section "Boot finalize" "$REPORT_DIR/boot_finalize.txt"
section "Ready to boot" "$REPORT_DIR/ready_to_boot.txt"
section "Image report" "$REPORT_DIR/image_report.txt"
section "Boot archive" "$REPORT_DIR/boot_archive_report.txt"
section "Partition report" "$REPORT_DIR/partition_report.txt"
section "Release bundle" "$REPORT_DIR/release_bundle_report.txt"
section "Build state validation" "$REPORT_DIR/build_state_validation.txt"
section "Build state" "$REPORT_DIR/build_state.txt"
section "Build state sync" "$REPORT_DIR/build_state_sync.txt"
section "Build log audit" "$REPORT_DIR/build_log_audit.txt"
section "Manifest coverage" "$REPORT_DIR/manifest_coverage.txt"
section "Build plan" "$REPORT_DIR/build_plan.txt"
section "Build plan validation" "$REPORT_DIR/build_plan_validation.txt"
section "Build queue status" "$REPORT_DIR/build_queue_status.txt"
section "Build queue retry" "$REPORT_DIR/build_queue_retry_report.txt"
section "Build queue sync" "$REPORT_DIR/build_queue_sync.txt"
section "Build queue state" "$REPORT_DIR/build_queue_state_validation.txt"
section "Build queue metrics" "$REPORT_DIR/build_queue_metrics.txt"
section "Build queue failures" "$REPORT_DIR/build_queue_failures.txt"
section "Build queue report" "$REPORT_DIR/build_queue_report.txt"
section "Build state snapshot" "$REPORT_DIR/build_state_snapshot.txt"
section "Build state snapshots" "$REPORT_DIR/build_state_snapshots.txt"
section "Build state prune" "$REPORT_DIR/build_state_prune.txt"
section "Build plan split" "$REPORT_DIR/build_plan_splits.txt"
section "Build dashboard" "$REPORT_DIR/build_dashboard.txt"
section "Build plan remaining" "$REPORT_DIR/build_plan_remaining.txt"
section "Build progress" "$REPORT_DIR/build_progress.txt"
section "Build progress rollup" "$REPORT_DIR/build_progress_rollup.txt"
section "Build progress failures" "$REPORT_DIR/build_progress_failures.txt"
section "Build orchestrator report" "$REPORT_DIR/build_orchestrator_report.txt"
section "Build orchestrator status" "$REPORT_DIR/build_orchestrator_status.txt"
section "Build orchestrator validation" "$REPORT_DIR/build_orchestrator_validation.txt"
section "Build health report" "$REPORT_DIR/build_health_report.txt"
section "Build gate" "$REPORT_DIR/build_gate.txt"
section "Build gate validate" "$REPORT_DIR/build_gate_validate.txt"
section "Build gate history" "$REPORT_DIR/build_gate_history.txt"
section "Build gate trend" "$REPORT_DIR/build_gate_trend.txt"
section "Build gate trend JSON" "$REPORT_DIR/build_gate_trend.json"
section "Build summary JSON" "$REPORT_DIR/build_summary.json"
section "Build summary report" "$REPORT_DIR/build_summary_report.txt"
section "Build summary report validate" "$REPORT_DIR/build_summary_report_validate.txt"
section "Build summary validate" "$REPORT_DIR/build_summary_validate.txt"
section "Build summary history" "$REPORT_DIR/build_summary_history.txt"
section "Build summary trend" "$REPORT_DIR/build_summary_trend.txt"
section "Build summary trend JSON" "$REPORT_DIR/build_summary_trend.json"
section "Build summary alerts" "$REPORT_DIR/build_summary_alerts.txt"
section "Build summary alerts JSON" "$REPORT_DIR/build_summary_alerts.json"
section "Build summary alerts validate" "$REPORT_DIR/build_summary_alerts_validate.txt"
section "Build summary alerts items" "$REPORT_DIR/build_summary_alerts_items.txt"
section "Build summary alerts items JSON" "$REPORT_DIR/build_summary_alerts_items.json"
section "Build summary alerts items validate" "$REPORT_DIR/build_summary_alerts_items_validate.txt"
section "Build summary alerts items history" "$REPORT_DIR/build_summary_alerts_items_history.txt"
section "Build summary alerts items history validate" "$REPORT_DIR/build_summary_alerts_items_history_validate.txt"
section "Build summary alerts items trend" "$REPORT_DIR/build_summary_alerts_items_trend.txt"
section "Build summary alerts items trend JSON" "$REPORT_DIR/build_summary_alerts_items_trend.json"
section "Build summary alerts items trend validate" "$REPORT_DIR/build_summary_alerts_items_trend_validate.txt"
section "Build summary alerts items delta" "$REPORT_DIR/build_summary_alerts_items_delta.txt"
section "Build summary alerts items delta JSON" "$REPORT_DIR/build_summary_alerts_items_delta.json"
section "Build summary alerts items delta validate" "$REPORT_DIR/build_summary_alerts_items_delta_validate.txt"
section "Build summary alerts items report" "$REPORT_DIR/build_summary_alerts_items_report.txt"
section "Build summary alerts items report validate" "$REPORT_DIR/build_summary_alerts_items_report_validate.txt"
section "Build summary alerts items report JSON" "$REPORT_DIR/build_summary_alerts_items_report.json"
section "Build summary alerts items report JSON validate" "$REPORT_DIR/build_summary_alerts_items_report_json_validate.txt"
section "Build summary alerts items report MD" "$REPORT_DIR/build_summary_alerts_items_report.md"
section "Build summary alerts items report MD validate" "$REPORT_DIR/build_summary_alerts_items_report_md_validate.txt"
section "Build summary alerts items overview" "$REPORT_DIR/build_summary_alerts_items_overview.txt"
section "Build summary alerts items overview JSON" "$REPORT_DIR/build_summary_alerts_items_overview.json"
section "Build summary alerts items overview validate" "$REPORT_DIR/build_summary_alerts_items_overview_validate.txt"
section "Build summary alerts stats" "$REPORT_DIR/build_summary_alerts_stats.txt"
section "Build summary alerts stats JSON" "$REPORT_DIR/build_summary_alerts_stats.json"
section "Build summary alerts stats validate" "$REPORT_DIR/build_summary_alerts_stats_validate.txt"
section "Build summary alerts stats history" "$REPORT_DIR/build_summary_alerts_stats_history.txt"
section "Build summary alerts stats history validate" "$REPORT_DIR/build_summary_alerts_stats_history_validate.txt"
section "Build summary alerts stats history report" "$REPORT_DIR/build_summary_alerts_stats_history_report.txt"
section "Build summary alerts stats history report JSON" "$REPORT_DIR/build_summary_alerts_stats_history_report.json"
section "Build summary alerts stats history report validate" "$REPORT_DIR/build_summary_alerts_stats_history_report_validate.txt"
section "Build summary alerts stats history report MD" "$REPORT_DIR/build_summary_alerts_stats_history_report.md"
section "Build summary alerts stats history report MD validate" "$REPORT_DIR/build_summary_alerts_stats_history_report_md_validate.txt"
section "Build summary alerts stats history report HTML" "$REPORT_DIR/build_summary_alerts_stats_history_report.html"
section "Build summary alerts stats history report HTML validate" "$REPORT_DIR/build_summary_alerts_stats_history_report_html_validate.txt"
section "Build summary alerts stats history table" "$REPORT_DIR/build_summary_alerts_stats_history_table.txt"
section "Build summary alerts stats history table validate" "$REPORT_DIR/build_summary_alerts_stats_history_table_validate.txt"
section "Build summary alerts stats history table CSV" "$REPORT_DIR/build_summary_alerts_stats_history_table.csv"
section "Build summary alerts stats history table MD" "$REPORT_DIR/build_summary_alerts_stats_history_table.md"
section "Build summary alerts stats history table MD validate" "$REPORT_DIR/build_summary_alerts_stats_history_table_md_validate.txt"
section "Build summary alerts stats history table HTML" "$REPORT_DIR/build_summary_alerts_stats_history_table.html"
section "Build summary alerts stats history table HTML validate" "$REPORT_DIR/build_summary_alerts_stats_history_table_html_validate.txt"
section "Build summary alerts stats history score" "$REPORT_DIR/build_summary_alerts_stats_history_score.txt"
section "Build summary alerts stats history score validate" "$REPORT_DIR/build_summary_alerts_stats_history_score_validate.txt"
section "Build summary alerts stats history anomalies" "$REPORT_DIR/build_summary_alerts_stats_history_anomalies.txt"
section "Build summary alerts stats history anomalies JSON" "$REPORT_DIR/build_summary_alerts_stats_history_anomalies.json"
section "Build summary alerts stats history anomalies rows" "$REPORT_DIR/build_summary_alerts_stats_history_anomalies_rows.csv"
section "Build summary alerts stats history anomalies validate" "$REPORT_DIR/build_summary_alerts_stats_history_anomalies_validate.txt"
section "Build summary alerts stats history anomalies MD" "$REPORT_DIR/build_summary_alerts_stats_history_anomalies.md"
section "Build summary alerts stats history anomalies MD validate" "$REPORT_DIR/build_summary_alerts_stats_history_anomalies_md_validate.txt"
section "Build summary alerts stats history anomalies HTML" "$REPORT_DIR/build_summary_alerts_stats_history_anomalies.html"
section "Build summary alerts stats history anomalies HTML validate" "$REPORT_DIR/build_summary_alerts_stats_history_anomalies_html_validate.txt"
section "Build summary alerts stats history rollup" "$REPORT_DIR/build_summary_alerts_stats_history_rollup.txt"
section "Build summary alerts stats history rollup JSON" "$REPORT_DIR/build_summary_alerts_stats_history_rollup.json"
section "Build summary alerts stats history rollup validate" "$REPORT_DIR/build_summary_alerts_stats_history_rollup_validate.txt"
section "Build summary alerts stats history rollup MD" "$REPORT_DIR/build_summary_alerts_stats_history_rollup.md"
section "Build summary alerts stats history rollup MD validate" "$REPORT_DIR/build_summary_alerts_stats_history_rollup_md_validate.txt"
section "Build summary alerts stats history rollup HTML" "$REPORT_DIR/build_summary_alerts_stats_history_rollup.html"
section "Build summary alerts stats history rollup HTML validate" "$REPORT_DIR/build_summary_alerts_stats_history_rollup_html_validate.txt"
section "Build summary alerts stats history rollup score" "$REPORT_DIR/build_summary_alerts_stats_history_rollup_score.txt"
section "Build summary alerts stats history rollup score JSON" "$REPORT_DIR/build_summary_alerts_stats_history_rollup_score.json"
section "Build summary alerts stats history rollup score validate" "$REPORT_DIR/build_summary_alerts_stats_history_rollup_score_validate.txt"
section "Build summary alerts stats history rollup score MD" "$REPORT_DIR/build_summary_alerts_stats_history_rollup_score.md"
section "Build summary alerts stats history rollup score MD validate" "$REPORT_DIR/build_summary_alerts_stats_history_rollup_score_md_validate.txt"
section "Build summary alerts stats history rollup score HTML" "$REPORT_DIR/build_summary_alerts_stats_history_rollup_score.html"
section "Build summary alerts stats history rollup score HTML validate" "$REPORT_DIR/build_summary_alerts_stats_history_rollup_score_html_validate.txt"
section "Build summary alerts stats history rollup bundle" "$REPORT_DIR/build_summary_alerts_stats_history_rollup_bundle.txt"
section "Build summary alerts stats history rollup bundle validate" "$REPORT_DIR/build_summary_alerts_stats_history_rollup_bundle_validate.txt"
section "Build summary alerts stats history rollup overview" "$REPORT_DIR/build_summary_alerts_stats_history_rollup_overview.txt"
section "Build summary alerts stats history rollup overview JSON" "$REPORT_DIR/build_summary_alerts_stats_history_rollup_overview.json"
section "Build summary alerts stats history rollup overview validate" "$REPORT_DIR/build_summary_alerts_stats_history_rollup_overview_validate.txt"
section "Build summary alerts stats history rollup overview MD" "$REPORT_DIR/build_summary_alerts_stats_history_rollup_overview.md"
section "Build summary alerts stats history rollup overview MD validate" "$REPORT_DIR/build_summary_alerts_stats_history_rollup_overview_md_validate.txt"
section "Build summary alerts stats history rollup overview HTML" "$REPORT_DIR/build_summary_alerts_stats_history_rollup_overview.html"
section "Build summary alerts stats history rollup overview HTML validate" "$REPORT_DIR/build_summary_alerts_stats_history_rollup_overview_html_validate.txt"
section "Build summary alerts stats history rollup history" "$REPORT_DIR/build_summary_alerts_stats_history_rollup_history.txt"
section "Build summary alerts stats history rollup history CSV" "$REPORT_DIR/build_summary_alerts_stats_history_rollup_history.csv"
section "Build summary alerts stats history rollup history validate" "$REPORT_DIR/build_summary_alerts_stats_history_rollup_history_validate.txt"
section "Build summary alerts stats history rollup history MD" "$REPORT_DIR/build_summary_alerts_stats_history_rollup_history.md"
section "Build summary alerts stats history rollup history MD validate" "$REPORT_DIR/build_summary_alerts_stats_history_rollup_history_md_validate.txt"
section "Build summary alerts stats history rollup history HTML" "$REPORT_DIR/build_summary_alerts_stats_history_rollup_history.html"
section "Build summary alerts stats history rollup history HTML validate" "$REPORT_DIR/build_summary_alerts_stats_history_rollup_history_html_validate.txt"
section "Build summary alerts stats history rollup trend" "$REPORT_DIR/build_summary_alerts_stats_history_rollup_trend.txt"
section "Build summary alerts stats history rollup trend JSON" "$REPORT_DIR/build_summary_alerts_stats_history_rollup_trend.json"
section "Build summary alerts stats history rollup trend validate" "$REPORT_DIR/build_summary_alerts_stats_history_rollup_trend_validate.txt"
section "Build summary alerts stats history rollup trend MD" "$REPORT_DIR/build_summary_alerts_stats_history_rollup_trend.md"
section "Build summary alerts stats history rollup trend MD validate" "$REPORT_DIR/build_summary_alerts_stats_history_rollup_trend_md_validate.txt"
section "Build summary alerts stats history rollup trend HTML" "$REPORT_DIR/build_summary_alerts_stats_history_rollup_trend.html"
section "Build summary alerts stats history rollup trend HTML validate" "$REPORT_DIR/build_summary_alerts_stats_history_rollup_trend_html_validate.txt"
section "Build summary alerts stats trend" "$REPORT_DIR/build_summary_alerts_stats_trend.txt"
section "Build summary alerts stats trend JSON" "$REPORT_DIR/build_summary_alerts_stats_trend.json"
section "Build summary alerts stats trend validate" "$REPORT_DIR/build_summary_alerts_stats_trend_validate.txt"
section "Build summary alerts stats delta" "$REPORT_DIR/build_summary_alerts_stats_delta.txt"
section "Build summary alerts stats delta JSON" "$REPORT_DIR/build_summary_alerts_stats_delta.json"
section "Build summary alerts stats delta validate" "$REPORT_DIR/build_summary_alerts_stats_delta_validate.txt"
section "Build summary alerts stats report" "$REPORT_DIR/build_summary_alerts_stats_report.txt"
section "Build summary alerts stats report validate" "$REPORT_DIR/build_summary_alerts_stats_report_validate.txt"
section "Build summary alerts stats report JSON" "$REPORT_DIR/build_summary_alerts_stats_report.json"
section "Build summary alerts stats report JSON validate" "$REPORT_DIR/build_summary_alerts_stats_report_json_validate.txt"
section "Build summary alerts stats report MD" "$REPORT_DIR/build_summary_alerts_stats_report.md"
section "Build summary alerts stats report MD validate" "$REPORT_DIR/build_summary_alerts_stats_report_md_validate.txt"
section "Build summary alerts stats report HTML" "$REPORT_DIR/build_summary_alerts_stats_report.html"
section "Build summary alerts stats report HTML validate" "$REPORT_DIR/build_summary_alerts_stats_html_validate.txt"
section "Build summary alerts stats export" "$REPORT_DIR/build_summary_alerts_stats_export.txt"
section "Build summary alerts stats export validate" "$REPORT_DIR/build_summary_alerts_stats_export_validate.txt"
section "Build summary alerts history" "$REPORT_DIR/build_summary_alerts_history.txt"
section "Build summary alerts trend" "$REPORT_DIR/build_summary_alerts_trend.txt"
section "Build summary alerts trend JSON" "$REPORT_DIR/build_summary_alerts_trend.json"
section "Build summary bundle" "$REPORT_DIR/build_summary_bundle.txt"
section "Build summary bundle validate" "$REPORT_DIR/build_summary_bundle_validate.txt"
section "Build summary bundle index" "$REPORT_DIR/build_summary_bundle_index.txt"
section "Build summary bundle index JSON" "$REPORT_DIR/build_summary_bundle_index.json"
section "Build summary bundle index validate" "$REPORT_DIR/build_summary_bundle_index_validate.txt"
section "Build summary bundle index history" "$REPORT_DIR/build_summary_bundle_index_history.txt"
section "Build summary bundle index history validate" "$REPORT_DIR/build_summary_bundle_index_history_validate.txt"
section "Build summary bundle index trend" "$REPORT_DIR/build_summary_bundle_index_trend.txt"
section "Build summary bundle index trend JSON" "$REPORT_DIR/build_summary_bundle_index_trend.json"
section "Build summary bundle index trend validate" "$REPORT_DIR/build_summary_bundle_index_trend_validate.txt"
section "Build summary bundle index delta" "$REPORT_DIR/build_summary_bundle_index_delta.txt"
section "Build summary bundle index delta JSON" "$REPORT_DIR/build_summary_bundle_index_delta.json"
section "Build summary bundle index delta validate" "$REPORT_DIR/build_summary_bundle_index_delta_validate.txt"
section "Build summary bundle index overview" "$REPORT_DIR/build_summary_bundle_index_overview.txt"
section "Build summary bundle index overview JSON" "$REPORT_DIR/build_summary_bundle_index_overview.json"
section "Build summary bundle index overview validate" "$REPORT_DIR/build_summary_bundle_index_overview_validate.txt"
section "Build summary bundle index score" "$REPORT_DIR/build_summary_bundle_index_score.txt"
section "Build summary bundle index score JSON" "$REPORT_DIR/build_summary_bundle_index_score.json"
section "Build summary bundle index score validate" "$REPORT_DIR/build_summary_bundle_index_score_validate.txt"
section "Build check report" "$REPORT_DIR/build_check_report.txt"
section "Build check status" "$REPORT_DIR/build_check_status_report.txt"
section "Build check rollup" "$REPORT_DIR/build_check_status_rollup.txt"
section "Build check gate" "$REPORT_DIR/build_check_gate.txt"
section "Build check trend" "$REPORT_DIR/build_check_trend.txt"
section "Build check prune" "$REPORT_DIR/build_check_prune.txt"
section "Build check stats" "$REPORT_DIR/build_check_stats.txt"
section "Build check regressions" "$REPORT_DIR/build_check_regressions.txt"
section "Build check regressions trend" "$REPORT_DIR/build_check_regressions_trend.txt"
section "Build check regressions trend JSON" "$REPORT_DIR/build_check_regressions_trend.json"
section "Build check regressions groups" "$REPORT_DIR/build_check_regressions_groups.txt"
section "Build check regressions groups JSON" "$REPORT_DIR/build_check_regressions_groups.json"
section "Build check regressions export" "$REPORT_DIR/build_check_regressions_export.txt"
section "Build check regressions top" "$REPORT_DIR/build_check_regressions_top.txt"
section "Build check regressions top JSON" "$REPORT_DIR/build_check_regressions_top.json"
section "Build check regressions summary" "$REPORT_DIR/build_check_regressions_summary.txt"
section "Build check regressions summary JSON" "$REPORT_DIR/build_check_regressions_summary.json"
section "Build check regressions summary validate" "$REPORT_DIR/build_check_regressions_summary_validate.txt"
section "Build check regressions index" "$REPORT_DIR/build_check_regressions_index.txt"
section "Build check regressions index JSON" "$REPORT_DIR/build_check_regressions_index.json"
section "Build check regressions report" "$REPORT_DIR/build_check_regressions_report.md"
section "Build check regressions report HTML" "$REPORT_DIR/build_check_regressions_report.html"
section "Build check regressions transitions" "$REPORT_DIR/build_check_regressions_transitions.txt"
section "Build check regressions transitions JSON" "$REPORT_DIR/build_check_regressions_transitions.json"
section "Build check regressions transitions validate" "$REPORT_DIR/build_check_regressions_transitions_validate.txt"
section "Build check regressions score" "$REPORT_DIR/build_check_regressions_score.txt"
section "Build check regressions score JSON" "$REPORT_DIR/build_check_regressions_score.json"
section "Build check regressions score validate" "$REPORT_DIR/build_check_regressions_score_validate.txt"
section "Build check regressions bundle" "$REPORT_DIR/build_check_regressions_bundle.txt"
section "Build check regressions bundle validate" "$REPORT_DIR/build_check_regressions_bundle_validate.txt"
section "Build check summary JSON" "$REPORT_DIR/build_check_summary.json"
section "Build check summary validate" "$REPORT_DIR/build_check_summary_validate.txt"
section "Build toolchain report" "$REPORT_DIR/build_toolchain_report.txt"
section "Build toolchain report JSON" "$REPORT_DIR/build_toolchain_report.json"
section "Build toolchain report validate" "$REPORT_DIR/build_toolchain_report_validate.txt"
section "Build toolchain session report" "$REPORT_DIR/build_toolchain_session_report.txt"
section "Build toolchain session report JSON" "$REPORT_DIR/build_toolchain_session_report.json"
section "Build toolchain session report validate" "$REPORT_DIR/build_toolchain_session_report_validate.txt"
section "Build check export CSV" "$REPORT_DIR/build_check_export.csv"
section "Build check regressions export CSV" "$REPORT_DIR/build_check_regressions_export.csv"
section "Build check coverage" "$REPORT_DIR/build_check_coverage.txt"
section "Build check snapshot" "$REPORT_DIR/build_check_snapshot.txt"
section "Build check snapshot list" "$REPORT_DIR/build_check_snapshot_list.txt"
section "Build check snapshot prune" "$REPORT_DIR/build_check_snapshot_prune.txt"
section "Build check snapshot diff" "$REPORT_DIR/build_check_snapshot_diff.txt"
section "Build times" "$REPORT_DIR/build_times.txt"
section "Status assessment" "$REPORT_DIR/status_assessment.txt"

echo "[OK] Summary report generated: $OUT_MD"
