# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 302e1b918c9c7974ba0275be76c3b8921198f151b7a9f4b3d76a7173adbfb68307349c1b7492e6831c85562c5630f3daeea21eded6dc4c08e572635bded1c318

test:
  secret_key_base: ce1b3504b8ce3dfad8b3d63029b02f3e4ce835de43559a437e4465f7dbafac747a6d03dc98622ba3591c1c7ec82d95b130eb6aaf1a4e202e4893d9e24f7c93e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
