source 'https://rubygems.org'

ruby '2.7.8'

gem 'rails', '5.2.8.1'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.2'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.5'
gem 'bootsnap', require: false

# Authentication
gem 'devise', '~> 4.7.0'

# File uploads
gem 'carrierwave', '~> 2.0'
gem 'cloudinary', '~> 1.20'

# Admin panel
gem 'rails_admin', '~> 2.0'

# Authorization and roles
gem 'cancancan', '~> 3.0'
gem 'rolify', '~> 6.0'

# Fake data generation
gem 'ffaker', '~> 2.20'

# Pagination
gem 'kaminari', '~> 1.2'

# Force compatible versions for Ruby 2.7
gem 'nokogiri', '~> 1.15.0'
gem 'ffi', '~> 1.15.5'

group :development, :test do
  gem 'sqlite3', '~> 1.6.0'
  gem 'byebug'
  gem 'rspec-rails', '~> 4.0'
  gem 'factory_bot_rails', '~> 5.0'
  gem 'capybara', '~> 3.35'
  gem 'database_cleaner-active_record', '~> 2.0'
end

group :development do
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '~> 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'rubycritic', require: false
end

group :production do
  gem 'pg', '~> 1.0'
end
