apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secrets
  namespace: ft-services
type: Opaque
data:
  mariadb-root-password: cm9vdHB3ZA==   # base64(rootpwd)
  mariadb-user: d3AtdXNlcg==             # wp-user
  mariadb-password: d3AtcGFzcw==         # wp-pass
  mariadb-database: d3AtZGI=             # wp-db
---
apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secrets
  namespace: ft-services
type: Opaque
data:
  db-name: d3AtZGI=
  db-user: d3AtdXNlcg==
  db-password: d3AtcGFzcw==
