# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a9a52cbeb120766cbe0d091eda5ac2068b41b36af5ae47d86716ae7494eba9afc0c7822da0122a129d2fe13d7206303f210b636729056c78680089a6bb93bf99

test:
  secret_key_base: b0c666337c1674863f37a9994375fa47bcdc08bcc80475bc3bde1b81be8cbb9f7065a0ec454c5a44cbe1b1bc4ae6599574cdcfc16b05137633e39003987cc947

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
