source 'https://rubygems.org'

ruby '~> 2.5'

gem 'rails', '4.2.11.3'
gem 'sqlite3', '~> 1.3.6'
gem 'sass-rails', '~> 5.0.6'
gem 'uglifier', '~> 2.7.2'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails', '~> 4.3.1'
gem 'turbolinks', '~> 2.5.3'
gem 'jbuilder', '~> 2.5.0'
gem 'bcrypt', '~> 3.1.11'
gem 'nokogiri', '~> 1.10.10'
gem 'sprockets', '~> 3.7.2'
gem 'ffi', '~> 1.15.5'
gem 'sassc', '~> 2.1.0'
gem 'loofah', '~> 2.2.3'
gem 'rails-html-sanitizer', '~> 1.0.4'

group :development, :test do
  gem 'byebug', '~> 9.0.6'
  gem 'minitest'
end

group :development do
  gem 'web-console', '~> 2.3.0'
  gem 'spring', '~> 1.7.2'
end
